app = "fx9-bot"

[build]
  builder = "heroku/buildpacks:20"

[http_service]
  internal_port = 10001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1

[mounts]
  source = "botdata"
  destination = "/data"